FROM node:18-alpine

WORKDIR /app

COPY ../../package.json ./
COPY ../../package-lock.json ./

COPY package.json ./apps/sample-service/package.json

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
