version: '3.3'

services:
  sample-service:
    image: ghcr.io/coder-repository/sample-service:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apps/sample-service/Dockerfile
    container_name: sample-service
    ports:
      - "5000:5000"
    networks:
      - siakad-network

  postgres:
    image: postgres:13
    restart: always
    container_name: siakad-db
    shm_size: 256MB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coder-siakad
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "6432:5432"
    volumes:
      - postgres_siakad:/var/lib/postgresql/data
    networks:
      - siakad-network

  migrate:
    build:
      context: apps/db-migrate
      dockerfile: Dockerfile
    networks:
      - siakad-network
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/coder-siakad?sslmode=disable

  redis:
    image: redis:6
    container_name: siakad-redis
    ports:
      - "7379:6379"
    networks:
      - siakad-network

volumes:
  postgres_siakad:

networks:
  siakad-network:
