GET http://localhost:5004/api/v1/payment/history?status=verified
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxZmRkNDk3OC0yMWI2LTQ2MjgtYTI2NS0zNThmY2JhN2M3NGEiLCJlbWFpbCI6ImpvaG5kb2UxMjNAc3R1ZGVudC5hYy5pZCIsInVzZXJuYW1lIjoiam9obmRvZTEyMyIsInJvbGUiOiJTdHVkZW50Iiwicm9sZUlkIjoiU1REIiwibmltIjoiTHo1cENHTUtDeWFhQTh2SGdSTXFFVUpYUE1jWWRPIiwiaWF0IjoxNzEwNDcyODcwLCJleHAiOjE3MTA0NzY0NzB9.IT1IbbnKvaNtawRhUWhC-GWapVdgXbUsf0bQHfE5bnc