_format_version: "2.1"
_transform: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
services:
  - name: example-service
    url: https://mockbin.org
    routes:
      - name: public-route
        paths:
          - /api
        plugins:
          - name: auth
  - name: announcement-service
    # url: http://siakad-announcement-api.default.svc.cluster.local:5007
    url: http://announcement-service:5007
    plugins:
      - name: auth
    routes:
      - name: announcement-route
        paths:
          - /api/v1/announcement
        strip_path: false
        preserve_host: false
  - name: auth-service
    # url: http://siakad-auth-api.default.svc.cluster.local:5001
    url: http://auth-service:5001
    routes:
      - name: auth-route
        paths:
          - /api/v1/auth
        strip_path: false
        preserve_host: false
  - name: data-service
    # url: http://siakad-data-api.default.svc.cluster.local:5009
    url: http://data-service:5009
    plugins:
      - name: auth
    routes:
      - name: data-route
        paths:
          - /api/v1/data
        strip_path: false
        preserve_host: false
  - name: krs-service
    # url: http://siakad-krs-api.default.svc.cluster.local:5008
    url: http://krs-service:5005
    plugins:
      - name: auth
    routes:
      - name: krs-route
        paths:
          - /api/v1/krs
        strip_path: false
        preserve_host: false
  - name: payment-service
    # url: http://siakad-payment-api.default.svc.cluster.local:5004
    url: http://payment-service:5004
    plugins:
      - name: auth
    routes:
      - name: payment-route
        paths:
          - /api/v1/payment
        strip_path: false
        preserve_host: false
  - name: schedule-service
    # url: http://siakad-schedule-api.default.svc.cluster.local:5010
    url: http://schedule-service:5005
    plugins:
      - name: auth
    routes:
      - name: schedule-route
        paths:
          - /api/v1/schedule
        strip_path: false
        preserve_host: false
