
### Update User
PATCH  http://localhost:5003/api/v1/user/9c39e6b4-2581-4d2b-b1a1-337484b06642
Content-Type: application/json

{
  "username": "jhondoe",
  "email": "jhondoe@student.ac.id",
  "role_id": "STD"
}
