
### Update User
PATCH http://localhost:5003/api/v1/api/29e99e68-e255-40cf-8ba4-83588f82fb7f
Content-Type: application/json

{
  "username": "jhondoe",
  "email": "jhondoe@student.ac.id",
  "role_id": "STD"
}
