apiVersion: apps/v1
kind: Deployment
metadata:
  name: siakad-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siakad-auth-api
  template:
    metadata:
      labels:
        app: siakad-auth-api
    spec:
      containers:
        - name: siakad-auth-api
          image: ghcr.io/coder-repository/auth-service:20240328024536
          env:
            - name: JWT_SECRET
              value: ""
            - name: PORT
              value: "5001"
            - name: DB_HOST
              value: ""
            - name: DB_PORT
              value: ""
            - name: DB_USER
              value: ""
            - name: DB_PASSWORD
              value: ""
            - name: DB_NAME
              value: ""
            - name: DB_SSL
              value: "true"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: siakad-auth-api
spec:
  selector:
    app: siakad-auth-api
  ports:
    - port: 5001
      targetPort: 5001

