apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    name: ingress-service
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /api/v1/auth
            backend:
              service:
                name: siakad-auth-api
                port:
                  number: 5001
          - pathType: ImplementationSpecific
            path: /api/v1/payment
            backend:
              service:
                name: siakad-payment-api
                port:
                  number: 5004
          - pathType: ImplementationSpecific
            path: /api/v1/announcement
            backend:
              service:
                name: siakad-announcement-api
                port:
                  number: 5005
