apiVersion: apps/v1
kind: Deployment
metadata:
  name: siakad-payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siakad-payment-api
  template:
    metadata:
      labels:
        app: siakad-payment-api
    spec:
      containers:
        - name: siakad-payment-api
          image: ghcr.io/coder-repository/payment-service:20240328092639
          env:
            - name: PORT
              value: "5004"
            - name: DB_HOST
              value: ""
            - name: DB_PORT
              value: ""
            - name: DB_USERNAME
              value: ""
            - name: DB_PASSWORD
              value: ""
            - name: DB_DATABASE
              value: ""
            - name: DB_SSL_MODE
              value: "require"
            - name: CLOUDINARY_CLOUD_NAME
              value: ""
            - name: CLOUDINARY_API_KEY
              value: ""
            - name: CLOUDINARY_API_SECRET
              value: ""
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: siakad-payment-api
spec:
  selector:
    app: siakad-payment-api
  ports:
    - port: 5004
      targetPort: 5004

