apiVersion: apps/v1
kind: Deployment
metadata:
  name: siakad-payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siakad-payment-api
  template:
    metadata:
      labels:
        app: siakad-payment-api
    spec:
      containers:
        - name: siakad-payment-api
          image: ghcr.io/coder-repository/payment-service:20240328092639
          env:
            - name: PORT
              value: "5004"
            - name: DB_HOST
              value: "ep-raspy-glitter-a1fuh4un-pooler.ap-southeast-1.aws.neon.tech"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: oktariorifqi
            - name: DB_PASSWORD
              value: WbVHOqg0m6Gw
            - name: DB_DATABASE
              value: coder-siakad
            - name: DB_SSL_MODE
              value: "require"
            - name: CLOUDINARY_CLOUD_NAME
              value: dsgv7kpmq
            - name: CLOUDINARY_API_KEY
              value: "211669514833157"
            - name: CLOUDINARY_API_SECRET
              value: 0w1ckZHtqg8Uyp9zfOwmVZJv4w8
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: siakad-payment-api
spec:
  selector:
    app: siakad-payment-api
  ports:
    - port: 5004
      targetPort: 5004

