CREATE TABLE IF NOT EXISTS role (
    role_id VARCHAR(10) NOT NULL PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL,
    role_description VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)