INSERT INTO study_program (study_program_name, faculty_id)
VALUES ('Ilmu Komputer', 1),
       ('Administrasi Bisnis', 3),
       ('Teknik Elektro', 1),
       ('Teknik Mesin', 1),
       ('Psikologi', 5),
       ('Biologi', 1),
       ('Matematika', 1),
       ('Sastra Inggris', 9),
       ('Ilmu Politik', 2),
       ('Ekonomi', 3),
       ('Teknik Kimia', 1),
       ('Fisika', 1),
       ('Sejarah', 9),
       ('Sosiologi', 2),
       ('Filosofi', 9),
       ('Ilmu Lingkungan', 1),
       ('Desain Grafis', 1),
       ('Teknologi Informasi', 1),
       ('Keamanan Siber', 1),
       ('Kecerdasan Buatan', 1),
       ('Ilmu Data', 1),
       ('Keperawatan', 6),
       ('Farmasi', 6),
       ('Teknik Sipil', 1),
       ('Arsitektur', 1),
       ('Pendidikan', 9),
       ('Manajemen Perhotelan', 3),
       ('Manajemen Pariwisata', 3),
       ('Akuntansi', 3),
       ('Keuangan', 3),
       ('Hubungan Internasional', 2),
       ('Hukum', 4),
       ('Kedokteran', 7),
       ('Kedokteran Gigi', 7),
       ('Kesehatan Masyarakat', 7),
       ('Kedokteran Hewan', 6),
       ('Pertanian', 8),
       ('Kehutanan', 8),
       ('Desain Fashion', 9),
       ('Desain Interior', 9),
       ('Jurnalisme', 10),
       ('Komunikasi Massa', 10),
       ('Musik', 9),
       ('Seni Teater', 9),
       ('Film', 9);