apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: siakad-auth
plugin: jwt
config:
  uri_param_names:
    - paramName_2.2.x
  claims_to_verify:
    - exp
---
apiVersion: v1
kind: Secret
metadata:
  name: siakad-token
  labels:
    konghq.com/credential: jwt
stringData:
  algorithm: "HS256"
  secret: "c70012035ab511e9c577c63366878648546aa5361537063306161537177330ad"
  key: "siakad-service"
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: siakad-consumer-auth
  annotations:
    kubernetes.io/ingress.class: kong
username: johndoe
credentials:
  - siakad-token