apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: siakad-cors
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  credentials: true