name: Docker Image Sample Service

on:
  push:
    branches: [ "staging/sprint-1" ]
    paths:
      - 'apps/sample-service/**'

jobs:
  build_and_publish_sample_service:
    runs-on: ubuntu-latest
    steps:
#      Uncomment this if you are testing gh workflow on local machine using 'act'
#      - uses: KengoTODA/actions-setup-docker-compose@v1
#        name: Install `docker-compose` for local simulations
#        with:
#          version: '2.14.2'
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          docker login --username rifqio --password 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 ghcr.io
          docker-compose build sample-service
          docker push ghcr.io/coder-repository/sample-service:latest

