name: Docker Mock Service

on:
  push:
    branches:
      - "staging/sprint-2"
    paths:
      - 'apps/mock-service/**'

jobs:
  build_and_publish_sample_service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: coder-automation
          password: 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

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate random tag ID
        id: random_tag
        run: echo "::set-output name=random_tag::$(date +%s)-$(echo $RANDOM)"

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/mock-service/Dockerfile
          push: true
          tags: ghcr.io/coder-repository/mock-service:${{ steps.random_tag.outputs.random_tag }}