name: Docker Image Announcement Service

on:
  push:
    branches:
      - "staging/sprint-2"
    paths:
      - 'apps/announcement-service/**'

jobs:
  build_and_publish_announcement_service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: coder-automation
          password: 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

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine the next version
        id: version
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/announcement-service
          file: apps/announcement-service/Dockerfile
          push: true
          tags: ghcr.io/coder-repository/announcement-service:${{ steps.version.outputs.date }}
