name: Docker Image Payment Service

on:
  push:
    branches:
      - "staging/sprint-2"
    paths:
      - 'apps/payment-service/**'

jobs:
  build_and_publish_payment_service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: coder-automation
          password: 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

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine the next version
        id: version
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: List files in context directory
        run: ls -l ./apps/payment-service

      - name: Build and push image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./apps/payment-service
          file: apps/payment-service/Dockerfile
          push: true
          tags: ghcr.io/coder-repository/payment-service:${{ steps.version.outputs.date }}
